import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bookmark, Copy, FileText, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { money, quoteApi, type QuoteResponse } from "./QuotePanel";

type Reservation = { id: string; status: "pending" | "approved" | "rejected" } | null;
type SavedQuote = { id: string; clientName: string; creatorName: string; createdAt: string; expiresAt: string; commissionRate: string; selectedQuotas: QuoteResponse["quotas"]; summary: QuoteResponse["summary"]; reservation: Reservation };
type Detail = SavedQuote & { quotas: QuoteResponse["quotas"]; commercialText: string };
export default function QuotesPage() {
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const list = useQuery<{ items: SavedQuote[] }>({ queryKey: ["saved-quotes"], queryFn: () => quoteApi("/saved") });
  const detail = useQuery<{ item: Detail }>({ queryKey: ["saved-quote", selectedId], queryFn: () => quoteApi(`/saved/${selectedId}`), enabled: !!selectedId });
  const remove = useMutation({ mutationFn: (id: string) => quoteApi(`/saved/${id}`, { method: "DELETE" }), onSuccess: () => { setSelectedId(null); void queryClient.invalidateQueries({ queryKey: ["saved-quotes"] }); toast.success("Cotação excluída"); } });
  const reserve = useMutation({ mutationFn: (id: string) => quoteApi(`/saved/${id}/reserve`, { method: "POST" }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["saved-quotes"] }); void detail.refetch(); toast.success("Pedido de reserva enviado"); } });
  async function copy() { if (!detail.data) return; await navigator.clipboard.writeText(detail.data.item.commercialText); toast.success("Cotação comercial copiada"); }
  return <section className="quotes-page"><span className="eyebrow">HISTÓRICO COMERCIAL</span><h1>Cotações salvas</h1><p>Consulte as condições registradas e copie novamente quando precisar.</p><div className="quotes-list panel">{list.isLoading && <div className="table-message">Carregando cotações…</div>}{list.error && <div className="auth-error">{list.error.message}</div>}{list.data?.items.map(item => <button className="quote-list-row" key={item.id} onClick={() => setSelectedId(item.id)}><span className="quote-list-icon"><FileText size={19} /></span><span><strong>{item.clientName}</strong><small>{new Date(item.createdAt).toLocaleString("pt-BR")} • {item.creatorName}</small></span><span><small>Crédito</small><strong>{money(item.summary.creditTotal)}</strong></span><span><small>Entrada</small><strong>{money(item.summary.finalEntryTotal)}</strong></span></button>)}{list.data?.items.length === 0 && <div className="table-message">Nenhuma cotação salva.</div>}</div>
    {selectedId && <div className="modal-backdrop"><div className="quote-detail-card"><div className="modal-heading"><div><span className="eyebrow">COTAÇÃO SALVA</span><h2>{detail.data?.item.clientName ?? "Carregando…"}</h2></div><button className="icon-button" onClick={() => setSelectedId(null)}><X size={19} /></button></div>{detail.error && <div className="auth-error">{detail.error.message}</div>}{detail.data && <><p className="detail-meta">Salva por {detail.data.item.creatorName} em {new Date(detail.data.item.createdAt).toLocaleString("pt-BR")}</p><div className="quote-detail-grid"><div><h3>Cotas</h3>{detail.data.item.quotas.map(quota => <div className="detail-quota" key={quota.id}><span><strong>{quota.code}</strong><small>{quota.category} • {quota.administrator}</small></span><strong>{money(quota.creditAmount)}</strong></div>)}<h3>Prazo e parcelas</h3>{detail.data.item.summary.installmentCascade.map(period => <div className="cascade-row" key={`${period.from}-${period.to}`}><span>{period.from}ª à {period.to}ª parcela</span><strong>{money(period.amount)}</strong></div>)}</div><div className="summary-list"><p><span>Crédito total</span><strong>{money(detail.data.item.summary.creditTotal)}</strong></p><p><span>Entrada original</span><strong>{money(detail.data.item.summary.baseEntryTotal)}</strong></p><p><span>Comissão ({Number(detail.data.item.commissionRate).toFixed(1).replace(".", ",")}%)</span><strong>{money(detail.data.item.summary.commissionTotal)}</strong></p><p className="final-entry"><span>Entrada reajustada</span><strong>{money(detail.data.item.summary.finalEntryTotal)}</strong></p><p><span>Saldo devedor</span><strong>{money(detail.data.item.summary.outstandingBalanceTotal)}</strong></p><p><span>Taxa de transferência</span><strong>{money(detail.data.item.summary.transferFeeTotal)}</strong></p><p><span>Seguro estimado</span><strong>{money(detail.data.item.summary.insuranceTotal)}</strong></p></div></div><button className="copy-button" onClick={() => void copy()}><Copy size={18} /> Copiar cotação</button></>}</div></div>}
    {selectedId && detail.data && <div className="quote-admin-actions"><button className="secondary-button" onClick={() => { sessionStorage.setItem("sa-capital-selected-quotas", JSON.stringify(detail.data!.item.quotas.map(q => q.id))); window.location.href = "/estoque"; }}><Plus size={17} /> Adicionar cotas</button><button className="secondary-button" disabled={!!detail.data.item.reservation || reserve.isPending} onClick={() => reserve.mutate(selectedId)}><Bookmark size={17} /> {detail.data.item.reservation ? `Reserva: ${detail.data.item.reservation.status}` : "Solicitar reserva"}</button><button className="danger-button" disabled={remove.isPending} onClick={() => { if (window.confirm("Excluir esta cotação permanentemente?")) remove.mutate(selectedId); }}><Trash2 size={17} /> Excluir</button></div>}
  </section>;
}
