import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Copy, Save, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";

export type QuoteResponse = { quotas: { id: string; code: string; category: string; administrator: string; creditAmount: string | number; entryAmount: string | number; installmentCount: number; installmentAmount: string | number; outstandingBalance: string | number }[]; summary: { creditTotal: number; baseEntryTotal: number; commissionRate: number; commissionTotal: number; finalEntryTotal: number; entryPercentage: number; outstandingBalanceTotal: number; transferFeeTotal: number; insuranceTotal: number; installmentCascade: { from: number; to: number; amount: number }[] }; commercialText: string };
export const money = (value: number | string) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value));
export async function quoteApi(path: string, options?: RequestInit) { const response = await fetch(`/api/quotes${path}`, { credentials: "same-origin", ...options, headers: options?.body ? { "Content-Type": "application/json", ...options.headers } : options?.headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível concluir a operação"); return data; }

export default function QuotePanel({ ids, onClose }: { ids: string[]; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [commissionRate, setCommissionRate] = useState(() => {
    const saved = Number(sessionStorage.getItem("sa-capital-commission-rate"));
    return Number.isInteger(saved) && saved >= 1 && saved <= 8 ? saved : 1;
  });
  const [saving, setSaving] = useState(false);
  const [clientName, setClientName] = useState("");
  const quote = useQuery<QuoteResponse>({ queryKey: ["quote-calculation", ids, commissionRate], queryFn: () => quoteApi("/calculate", { method: "POST", body: JSON.stringify({ quotaIds: ids, commissionRate }) }), retry: false });
  const save = useMutation({ mutationFn: () => quoteApi("/saved", { method: "POST", body: JSON.stringify({ clientName, quotaIds: ids, commissionRate }) }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["saved-quotes"] }); toast.success("Cotação salva"); setSaving(false); setClientName(""); } });
  function updateCommission(value: number) { setCommissionRate(value); sessionStorage.setItem("sa-capital-commission-rate", String(value)); }
  async function copy() { if (!quote.data) return; await navigator.clipboard.writeText(quote.data.commercialText); toast.success("Cotação comercial copiada"); }
  return <div className="modal-backdrop quote-backdrop"><div className="quote-floating-card"><div className="modal-heading"><div><span className="eyebrow">COTAÇÃO</span><h2>Condição calculada</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div>
    {quote.isLoading && <div className="table-message">Calculando…</div>}{quote.error && <div className="auth-error">{quote.error.message}</div>}{quote.data && <><div className="summary-highlight"><span>Crédito total</span><strong>{money(quote.data.summary.creditTotal)}</strong></div><div className="quote-codes">{quote.data.quotas.map(item => <span key={item.id}>{item.code}</span>)}</div><label className="commission-control"><span>Adicionar comissão</span><select value={commissionRate} onChange={event => updateCommission(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7, 8].map(rate => <option key={rate} value={rate}>{rate}%</option>)}</select></label><div className="summary-list"><p><span>Entrada original</span><strong>{money(quote.data.summary.baseEntryTotal)}</strong></p><p><span>Comissão</span><strong>{money(quote.data.summary.commissionTotal)}</strong></p><p className="final-entry"><span>Entrada reajustada</span><strong>{money(quote.data.summary.finalEntryTotal)}</strong><small>{quote.data.summary.entryPercentage.toFixed(2).replace(".", ",")}% do crédito</small></p>{quote.data.summary.installmentCascade.map(period => <p key={`${period.from}-${period.to}`}><span>{period.from}ª à {period.to}ª parcela</span><strong>{money(period.amount)}</strong></p>)}</div><div className="quote-actions"><button className="secondary-button" onClick={() => void copy()}><Copy size={17} /> Copiar cotação</button><button className="primary-button button-reset" onClick={() => setSaving(true)}><Save size={17} /> Salvar cotação</button></div><div className="privacy-note"><Check size={15} /><span>O texto copiado usa a entrada reajustada, sem revelar a comissão.</span></div></>}
    {saving && <div className="nested-modal-backdrop"><form className="client-name-card" onSubmit={(event: FormEvent) => { event.preventDefault(); save.mutate(); }}><div className="modal-heading"><div><span className="eyebrow">SALVAR COTAÇÃO</span><h2>Identificar cliente</h2></div><button type="button" className="icon-button" onClick={() => setSaving(false)}><X size={18} /></button></div><label>Nome do cliente<input autoFocus minLength={2} maxLength={180} required value={clientName} onChange={event => setClientName(event.target.value)} /></label>{save.error && <div className="auth-error">{save.error.message}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => setSaving(false)}>Cancelar</button><button className="primary-button button-reset" disabled={save.isPending}>{save.isPending ? "Salvando…" : "Salvar"}</button></div></form></div>}
  </div></div>;
}
