import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { FileText, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { administratorInputSchema, documentTypes, imageTypes, maxAttachmentBytes, type Administrator, type AdministratorInput } from "@shared/administrators";
import { dismissBackdrop } from "../../lib/dismissBackdrop";

async function readFile(file: File): Promise<AdministratorInput["documents"][number]> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Não foi possível ler o arquivo")); reader.onload = () => resolve({ name: file.name, mimeType: file.type as AdministratorInput["documents"][number]["mimeType"], base64: String(reader.result).split(",")[1] }); reader.readAsDataURL(file); }); }

export default function AdministratorFormModal({ initial, onClose, onSaved }: { initial: Administrator | null; onClose: () => void; onSaved: (item: Administrator) => void }) {
  const [sending, setSending] = useState(false); const [name, setName] = useState(initial?.name ?? ""); const [characteristics, setCharacteristics] = useState(initial?.characteristics ?? ""); const [website, setWebsite] = useState(initial?.website ?? ""); const [logoFile, setLogoFile] = useState<File>(); const [documents, setDocuments] = useState<File[]>([]); const [logoPreview, setLogoPreview] = useState<string>();
  useEffect(() => { if (!logoFile) { setLogoPreview(undefined); return; } const url = URL.createObjectURL(logoFile); setLogoPreview(url); return () => URL.revokeObjectURL(url); }, [logoFile]);
  const close = () => { if (!sending) onClose(); };
  function handleLogo(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!imageTypes.includes(file.type as typeof imageTypes[number]) || file.size > maxAttachmentBytes) { event.target.value = ""; toast.error("Selecione PNG, JPEG ou WebP de até 10 MB"); return; } setLogoFile(file); }
  function handleDocuments(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []); if (files.length > 10 || files.some(file => !documentTypes.includes(file.type as typeof documentTypes[number]))) { toast.error("Selecione até 10 documentos nos formatos indicados"); event.target.value = ""; return; } setDocuments(files); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (sending) return; if ([...(logoFile ? [logoFile] : []), ...documents].reduce((sum, file) => sum + file.size, 0) > maxAttachmentBytes) return void toast.error("Os arquivos juntos devem ter no máximo 10 MB"); setSending(true); try { const input = administratorInputSchema.safeParse({ name, characteristics, website, logo: logoFile ? await readFile(logoFile) : undefined, documents: await Promise.all(documents.map(readFile)) }); if (!input.success) throw new Error(input.error.issues[0]?.message); const response = await fetch(`/api/administrators${initial ? `/${initial.id}` : ""}`, { method: initial ? "PUT" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input.data) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível concluir a operação"); toast.success("Administradora salva com sucesso"); onSaved(data.item); } catch (error) { toast.error((error as Error).message); } finally { setSending(false); } }
  return <div className="modal-backdrop" {...dismissBackdrop(close, sending)}><div className="administrator-modal" role="dialog" aria-modal="true" aria-label={initial ? "Editar administradora" : "Adicionar administradora"}><div className="modal-heading"><div><span className="eyebrow">{initial ? "EDITAR ADMINISTRADORA" : "NOVA ADMINISTRADORA"}</span><h2>{initial ? "Editar administradora" : "Adicionar administradora"}</h2></div><button type="button" className="icon-button" onClick={close} disabled={sending}><X size={18} /></button></div><form className="administrator-form" onSubmit={submit}><label>Logo<div className="administrator-logo-upload">{(logoPreview || initial?.logo) ? <img src={logoPreview || initial?.logo} alt="Pré-visualização" /> : <><Upload size={24} /><span>Selecionar logo</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleLogo} disabled={sending} /></div></label><label>Nome da administradora<input value={name} disabled={sending} minLength={2} maxLength={160} onChange={event => setName(event.target.value)} placeholder="Ex.: Porto Seguro" required /></label><label>Características<textarea value={characteristics} disabled={sending} maxLength={5000} onChange={event => setCharacteristics(event.target.value)} placeholder="Descreva as principais características, regras, segmentos..." required /></label><label>Link<input type="url" value={website} disabled={sending} maxLength={2000} onChange={event => setWebsite(event.target.value)} placeholder="https://..." /></label><label>Documentos<div className="administrator-document-upload"><FileText size={20} /><div><strong>Adicionar documentos</strong><span>PDF, Word, Excel, PNG, JPEG ou WebP. Total de até 10 MB com a logo.</span></div><input type="file" multiple accept={documentTypes.join(",")} disabled={sending} onChange={handleDocuments} /></div></label>{initial?.documents.length ? <div><p>Documentos já cadastrados (serão mantidos):</p><ul>{initial.documents.map(doc => <li key={doc.id}><a href={doc.url} target="_blank" rel="noreferrer">{doc.name}</a></li>)}</ul></div> : null}{documents.length > 0 && <ul>{documents.map((file, index) => <li key={index}>{file.name}</li>)}</ul>}<div className="form-actions"><button type="button" className="secondary-button" onClick={close} disabled={sending}>Cancelar</button><button type="submit" disabled={sending} className="primary-button">{sending ? "Salvando…" : "Salvar administradora"}</button></div></form></div></div>;
}
