import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { X } from "lucide-react";
import { toast } from "sonner";
import { dismissBackdrop } from "../../lib/dismissBackdrop";
import { stockApi, type QuotaRecord } from "./contracts";

const emptyForm = { code: "", category: "", administrator: "", supplier: "", creditAmount: "", entryAmount: "", installmentCount: "", installmentAmount: "", outstandingBalance: "", status: "available", featured: false };
export default function QuotaFormModal({ quota, onClose }: { quota?: QuotaRecord; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState(quota ? { ...quota, supplier: quota.supplier ?? "", creditAmount: String(quota.creditAmount), entryAmount: String(quota.entryAmount), installmentCount: String(quota.installmentCount), installmentAmount: String(quota.installmentAmount), outstandingBalance: String(quota.outstandingBalance) } : emptyForm);
  const save = useMutation({ mutationFn: () => stockApi(quota ? `/${quota.id}` : "", { method: quota ? "PATCH" : "POST", body: JSON.stringify(form) }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["stock"] }); void queryClient.invalidateQueries({ queryKey: ["stock-filters"] }); toast.success(quota ? "Cota atualizada" : "Cota cadastrada"); onClose(); } });
  const remove = useMutation({ mutationFn: () => stockApi(`/${quota!.id}`, { method: "DELETE" }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["stock"] }); toast.success("Cota excluída"); onClose(); } });
  const field = (key: keyof typeof form, value: string | boolean) => setForm(current => ({ ...current, [key]: value }));
  return <div className="modal-backdrop" {...dismissBackdrop(onClose)}><form className="stock-modal" onSubmit={event => { event.preventDefault(); save.mutate(); }}><div className="modal-heading"><div><span className="eyebrow">{quota ? "EDITAR COTA" : "NOVA COTA"}</span><h2>{quota ? quota.code : "Cadastrar no estoque"}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={19} /></button></div><div className="quota-form-grid"><label>Código<input value={form.code} onChange={event => field("code", event.target.value)} required /></label><label>Categoria<input value={form.category} onChange={event => field("category", event.target.value)} placeholder="Imóvel, veículo…" required /></label><label>Administradora<input value={form.administrator} onChange={event => field("administrator", event.target.value)} required /></label><label>Fornecedor<input value={form.supplier} onChange={event => field("supplier", event.target.value)} /></label><label>Crédito<input value={form.creditAmount} onChange={event => field("creditAmount", event.target.value)} placeholder="150.000,00" required /></label><label>Entrada<input value={form.entryAmount} onChange={event => field("entryAmount", event.target.value)} placeholder="30.000,00" required /></label><label>Nº parcelas<input type="number" min="1" value={form.installmentCount} onChange={event => field("installmentCount", event.target.value)} required /></label><label>Valor da parcela<input value={form.installmentAmount} onChange={event => field("installmentAmount", event.target.value)} placeholder="1.250,00" required /></label><label>Saldo devedor<input value={form.outstandingBalance} onChange={event => field("outstandingBalance", event.target.value)} required /></label><label>Situação<select value={form.status} onChange={event => field("status", event.target.value)}><option value="available">Disponível</option><option value="reserved">Reservada</option></select></label><label className="featured-check"><input type="checkbox" checked={form.featured} onChange={event => field("featured", event.target.checked)} /> Destacar esta condição</label></div>{save.error && <div className="auth-error">{save.error.message}</div>}<div className="form-actions">{quota && <button type="button" className="danger-button" disabled={remove.isPending} onClick={() => { if (window.confirm(`Excluir permanentemente a cota ${quota.code}?`)) remove.mutate(); }}>Excluir</button>}<button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button button-reset" disabled={save.isPending}>{save.isPending ? "Salvando…" : "Salvar cota"}</button></div></form></div>;
}
