import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { FileSpreadsheet, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { dismissBackdrop } from "../../lib/dismissBackdrop";
import { stockApi, type PreviewRow } from "./contracts";

function normalizedHeader(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]/g, ""); }
function rowValue(row: Record<string, unknown>, aliases: string[]) { return Object.entries(row).find(([key]) => aliases.includes(normalizedHeader(key)))?.[1] ?? ""; }
export function normalizeSpreadsheetRow(row: Record<string, unknown>) {
  const rawStatus = String(rowValue(row, ["situacao", "status"])).toLowerCase();
  return { code: String(rowValue(row, ["codcota", "codigocota", "codigo", "cota"])), category: String(rowValue(row, ["categoria"])), administrator: String(rowValue(row, ["administradora"])), supplier: String(rowValue(row, ["fornecedor"])), creditAmount: rowValue(row, ["credito", "valorcredito"]), entryAmount: rowValue(row, ["entrada", "valorentrada"]), installmentCount: rowValue(row, ["nparcelas", "numeroparcelas", "parcelas"]), installmentAmount: rowValue(row, ["vlrparcela", "valorparcela"]), outstandingBalance: rowValue(row, ["saldodevedor", "saldo"]), status: rawStatus.includes("vend") ? "sold" : rawStatus.includes("reserv") ? "reserved" : "available", featured: ["sim", "true", "1", "destaque"].includes(String(rowValue(row, ["destaque", "destacada"])).toLowerCase()) };
}

export default function StockImportModal({ onClose }: { onClose: () => void }) {
  const queryClient = useQueryClient(); const [rows, setRows] = useState<unknown[]>([]); const [fileName, setFileName] = useState(""); const [mode, setMode] = useState<"add" | "replace">("add");
  const preview = useMutation({ mutationFn: (data: unknown[]) => stockApi("/import/preview", { method: "POST", body: JSON.stringify({ rows: data }) }) });
  const commit = useMutation({ mutationFn: () => stockApi("/import/commit", { method: "POST", body: JSON.stringify({ rows, mode }) }), onSuccess: data => { void queryClient.invalidateQueries({ queryKey: ["stock"] }); void queryClient.invalidateQueries({ queryKey: ["stock-filters"] }); toast.success(`${data.imported} cotas processadas`); onClose(); } });
  async function chooseFile(file?: File) { if (!file) return; if (!file.size || file.size > 10 * 1024 * 1024) return void toast.error("Selecione uma planilha com ate 10 MB."); setFileName(file.name); try { const XLSX = await import("xlsx"); const workbook = XLSX.read(await file.arrayBuffer(), { type: "array" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const normalized = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }).map(normalizeSpreadsheetRow); setRows(normalized); preview.mutate(normalized); } catch { toast.error("Não foi possível ler a planilha"); } }
  const result = preview.data as { rows: PreviewRow[]; valid: number; invalid: number } | undefined;
  return <div className="modal-backdrop" {...dismissBackdrop(onClose)}><div className="stock-modal import-modal"><div className="modal-heading"><div><span className="eyebrow">IMPORTAR ESTOQUE</span><h2>Prévia da planilha</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><label className="file-drop"><FileSpreadsheet size={30} /><strong>{fileName || "Selecionar XLSX, XLS ou CSV"}</strong><span>A primeira linha deve conter os nomes das colunas.</span><input type="file" accept=".xlsx,.xls,.csv" onChange={event => void chooseFile(event.target.files?.[0])} /></label>{preview.isPending && <div className="table-message">Validando planilha…</div>}{preview.error && <div className="auth-error">{preview.error.message}</div>}{result && <><div className="import-summary"><span className="valid-count">{result.valid} válidas</span><span className={result.invalid ? "invalid-count" : "valid-count"}>{result.invalid} inválidas</span></div><div className="import-mode"><label><input type="radio" name="stock-import-mode" checked={mode === "add"} onChange={() => setMode("add")} /> Adicionar cotas ao estoque</label><label><input type="radio" name="stock-import-mode" checked={mode === "replace"} onChange={() => setMode("replace")} /> Substituir e apagar o estoque atual</label></div>{result.invalid > 0 && <div className="import-errors">{result.rows.filter(row => !row.valid).slice(0, 12).map(row => <p key={row.row}><strong>Linha {row.row}:</strong> {row.error}</p>)}</div>}<div className="form-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button button-reset" disabled={result.invalid > 0 || commit.isPending} onClick={() => { if (mode === "replace" && !window.confirm("Substituir o estoque disponível? Cotas reservadas e vinculadas a negociações serão preservadas, mesmo se constarem na nova planilha.")) return; commit.mutate(); }}><Upload size={17} /> {commit.isPending ? "Importando…" : "Confirmar importação"}</button></div></>}</div></div>;
}
